# NumPy

## How to import NumPy

In [1]:
import numpy as np

# Array

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Creating Array

In [ ]:
# np.array()
# np.zeros()
# np.ones()
# np.empty()
# np.arange()

In [7]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.empty(3)

array([1., 1., 1.])

In [11]:
np.arange(0, 8, 2) # start, stop, step

array([0, 2, 4, 6])

## Add, Remove, and Sort

In [ ]:
# np.append()
# np.delete()
# np.sort()

In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [13]:
np.append(arr, [6, 7])

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
np.delete(arr, 1)

array([1, 3, 4, 5])

In [15]:
arr = np.array([2, 5, 4, 3, 1])
print(arr)
print(np.sort(arr))

[2 5 4 3 1]
[1 2 3 4 5]


## Shape and Size

In [ ]:
# ndarray.ndim()
# ndarray.size()
# ndarray.shape()

In [16]:
arr_example = np.array([
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ],
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ],
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ]
])

print(arr_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [19]:
print(arr_example.ndim)
print(arr_example.size)
print(arr_example.shape)

3
24
(3, 2, 4)


## Reshape

In [20]:
# np.reshape()

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


## Convert 1D to 2D

In [ ]:
# np.newaxis()
# np.expand_dims()

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [24]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [25]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [26]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [29]:
b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [30]:
c = np.expand_dims(a, axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


## Indexing and Slicing

In [32]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2])

[1 2 3]
1
2
[1 2]
[2 3]
2


In [33]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [35]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [37]:
divisible_by_2 = a[a % 2 == 0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [38]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [ ]:
# slicing indexing
# np.vstack()
# np.hstack()
# np.hsplit()
# .view()
# .copy()

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [41]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [44]:
a_1 = np.array([
    [1, 1],
    [2, 2]
])
a_2 = np.array([
    [3, 3],
    [4, 4]
])

In [46]:
# vertikal
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [50]:
arrsplit = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,],
    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [51]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [52]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
b[0,0] = 0
print("array a")
print(a)
print("array b")
print(b)

# view bisa merubah si induk juga

array a
[[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array b
[[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Basic Array Operations

In [70]:
data1 = np.array([0, 1, 2])
data2 = np.array([4, 5, 6])

print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [71]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [73]:
b = np.array([
    [1, 1],
    [2, 2]
])
b

array([[1, 1],
       [2, 2]])

In [74]:
b.sum(axis=0)

array([3, 3])

In [75]:
b.sum(axis=1)

array([2, 4])

In [77]:
data = np.array([1, 2])
print("data \n",data)
ones = np.ones(2)
print("ones \n",ones)

data 
 [1 2]
ones 
 [1. 1.]


In [79]:
print(data + ones)
print(data - ones)
print(data * data)
print(data / data)

[2. 3.]
[0. 1.]
[1 4]
[1. 1.]


## Broadcasting

In [80]:
data * 2

array([2, 4])

## More Array Operations

In [ ]:
# data.max()
# data.min()
# data.sum()

In [81]:
A = np.array([
    [0.45053314, 0.17296777, 0.34376245, 0.5510652],
    [0.54627315, 0.05093587, 0.40067661, 0.55645993],
    [0.12697628, 0.82485143, 0.26590556, 0.56917101]
])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [83]:
print(A.sum())
print(A.max())
print(A.max(axis=1))
print(A.min())
print(A.min(axis=0))
print(A.std())

4.8595784
0.82485143
[0.5510652  0.55645993 0.82485143]
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]
0.21392120766089617


# Matrices

## Creting Matrices

In [84]:
np.array([
    [1, 2],
    [3, 4]
])

array([[1, 2],
       [3, 4]])

In [87]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(np.random.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.77924856 0.81586424]
 [0.86804375 0.1701689 ]
 [0.81372101 0.7157723 ]]


## Matrix Arithmetic

In [88]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [89]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [90]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [91]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [92]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [93]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [94]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [95]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [96]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [97]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [98]:
print(data.max(axis=0)) # horizontal
print(data.max(axis=1)) # vertikal

[5 6]
[2 4 6]


## Transposing and Reshaping

In [99]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [100]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [101]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [102]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

## N-Dimensional Array

In [107]:
ndarr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [108]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [109]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [110]:
print(np.random.random((4,3,2)))

[[[0.78804281 0.3140965 ]
  [0.89258232 0.09152609]
  [0.67909965 0.43463702]]

 [[0.15344568 0.458905  ]
  [0.51397456 0.37748265]
  [0.53219389 0.11525501]]

 [[0.47797753 0.02433455]
  [0.85048272 0.19129514]
  [0.28928653 0.39028319]]

 [[0.9265818  0.40935949]
  [0.71796227 0.91398667]
  [0.01489611 0.65197975]]]


## Flatten N-Dimensional Array

In [111]:
arrflat = np.array([
    [1, 2, 3, 4],
    [5, 4, 6, 7],
    [9, 10, 11, 12]
])
print(arrflat)

[[ 1  2  3  4]
 [ 5  4  6  7]
 [ 9 10 11 12]]


In [112]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  4,  6,  7,  9, 10, 11, 12])

# Working with Math Formulas

In [114]:
# error = (1/n) * np.sum(np.square(observed - prediction))